# ═══════════════════════════════════════════════════════════════════
# Docker Compose para Pgpool-II com Configuração Externalizada
# Autor: Eduardo Richard
# Versão: v2.0 (2025)
# ═══════════════════════════════════════════════════════════════════

services:
  pgpool:
    image: pgpool:latest
    container_name: ${PGPOOL_NAME:-pgpool}
    hostname: ${PGPOOL_NAME:-pgpool}
    build:
      context: ./infra/pgpool
    restart: unless-stopped
    entrypoint: /opt/pgpool/bin/scripts/entrypoint.sh
    command:
      - "/opt/pgpool/bin/pgpool"
      - "-n"
      - "-f"
      - "/opt/pgpool/etc/pgpool.conf"

    depends_on:
      patroni-postgres-1:
        condition: service_healthy
      patroni-postgres-2:
        condition: service_healthy
      patroni-postgres-3:
        condition: service_healthy
    
    healthcheck:
      test: 
      - "CMD-SHELL"
      - "PCPPASSFILE=/home/pgpool/.pcppass pcp_node_count -h localhost -p 9898 -U pcp_admin -w >/dev/null 2>&1 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - ./infra/pgpool/scripts:/opt/pgpool/bin/scripts:ro

      - ./infra/pgpool/config/pgpool.template.conf:/etc/pgpool2/pgpool.template.conf:ro
      - ./infra/pgpool/config/pool_hba.conf:/opt/pgpool/etc/pool_hba.conf:ro

      - pgpool2-logs:/var/log/pgpool

    env_file:
      - ./infra/pgpool/config/.pgpool.env

    ports:
      - "${PGPOOL_HOST_PORT:-5432}:5432"
      - "${PGPOOL_PCP_HOST_PORT:-9898}:9898"
      
    networks:
      - pg-ha-network

# ═══════════════════════════════════════════════════════════════════
# NOTA: Volumes e Networks são gerenciados pelo docker-compose.yaml principal
# ═══════════════════════════════════════════════════════════════════