# Cluster ETCD para Patroni
# Autor: Eduardo Richard
# Versão: v2.0 (2025)

# ═══════════════════════════════════════════════════════════════════
# ÂNCORAS YAML (Templates Reutilizáveis)
# ═══════════════════════════════════════════════════════════════════

x-etcd-common: &etcd-common
  image: gcr.io/etcd-development/etcd:v3.5.17
  networks:
    - pg-ha-network
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://127.0.0.1:2379"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 15s

# ═══════════════════════════════════════════════════════════════════
# SERVIÇOS
# ═══════════════════════════════════════════════════════════════════

services:

  # --- ETCD Node 1 ---
  etcd-1:
    <<: *etcd-common
    hostname: ${ETCD1_NAME}
    container_name: ${ETCD1_NAME}
    command:
      - /usr/local/bin/etcd
      - --name=${ETCD1_NAME}
      - --data-dir=/etcd-data
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://${ETCD1_NAME}:2379
      - --initial-advertise-peer-urls=http://${ETCD1_NAME}:2380
      - --initial-cluster=${ETCD1_NAME}=http://${ETCD1_NAME}:2380,${ETCD2_NAME}=http://${ETCD2_NAME}:2380,${ETCD3_NAME}=http://${ETCD3_NAME}:2380
      - --initial-cluster-token=patroni-etcd-cluster
      - --initial-cluster-state=new
    ports:
      - "${ETCD1_HOST_PORT:-2379}:2379"
      - "${ETCD1_PEER_PORT:-2380}:2380"
    volumes:
      - etcd-1-data:/etcd-data

  # --- ETCD Node 2 ---
  etcd-2:
    <<: *etcd-common
    hostname: ${ETCD2_NAME}
    container_name: ${ETCD2_NAME}
    command:
      - /usr/local/bin/etcd
      - --name=${ETCD2_NAME}
      - --data-dir=/etcd-data
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://${ETCD2_NAME}:2379
      - --initial-advertise-peer-urls=http://${ETCD2_NAME}:2380
      - --initial-cluster=${ETCD1_NAME}=http://${ETCD1_NAME}:2380,${ETCD2_NAME}=http://${ETCD2_NAME}:2380,${ETCD3_NAME}=http://${ETCD3_NAME}:2380
      - --initial-cluster-token=patroni-etcd-cluster
      - --initial-cluster-state=new
    ports:
      - "${ETCD2_HOST_PORT:-2479}:2379"
      - "${ETCD2_PEER_PORT:-2480}:2380"
    volumes:
      - etcd-2-data:/etcd-data

  # --- ETCD Node 3 ---
  etcd-3:
    <<: *etcd-common
    hostname: ${ETCD3_NAME}
    container_name: ${ETCD3_NAME}
    command:
      - /usr/local/bin/etcd
      - --name=${ETCD3_NAME}
      - --data-dir=/etcd-data
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://${ETCD3_NAME}:2379
      - --initial-advertise-peer-urls=http://${ETCD3_NAME}:2380
      - --initial-cluster=${ETCD1_NAME}=http://${ETCD1_NAME}:2380,${ETCD2_NAME}=http://${ETCD2_NAME}:2380,${ETCD3_NAME}=http://${ETCD3_NAME}:2380
      - --initial-cluster-token=patroni-etcd-cluster
      - --initial-cluster-state=new
    ports:
      - "${ETCD3_HOST_PORT:-2579}:2379"
      - "${ETCD3_PEER_PORT:-2580}:2380"
    volumes:
      - etcd-3-data:/etcd-data

# ═══════════════════════════════════════════════════════════════════
# VOLUMES
# ═══════════════════════════════════════════════════════════════════
volumes:
  etcd-1-data:
      name: etcd-1-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${ETCD1_DATA_PATH}
  etcd-2-data:
      name: etcd-2-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${ETCD2_DATA_PATH}
  etcd-3-data:
      name: etcd-3-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${ETCD3_DATA_PATH}

# ═══════════════════════════════════════════════════════════════════
# NETWORKS
# ═══════════════════════════════════════════════════════════════════
networks:
  pg-ha-network:
    name: ${NETWORK_NAME}
    driver: bridge
