# ═══════════════════════════════════════════════════════════════════
# Cluster PostgreSQL com Patroni - Arquivo Principal (Orquestrador)
# Autor: Eduardo Richard
# Versão: v2.0 (2025)
# ═══════════════════════════════════════════════════════════════════
# 
# Este arquivo utiliza a diretiva 'include' do Docker Compose v2.20+
# para carregar automaticamente todos os serviços segmentados.
#
# ESTRUTURA:
# - docker-compose.etcd.yaml    → Cluster ETCD (3 nós)
# - docker-compose.patroni.yaml → Cluster Patroni/PostgreSQL (3 nós)
# - docker-compose.pgpool.yaml  → PgPool-II (Load Balancer)
#
# USO:
#   docker compose up -d              # Sobe todos os serviços
#   docker compose down               # Para todos os serviços
#   docker compose ps                 # Lista status dos serviços
#   docker compose logs -f [service]  # Visualiza logs
#
# ═══════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════
# INCLUDES - Importa arquivos segmentados
# ═══════════════════════════════════════════════════════════════════
include:
  - docker-compose.etcd.yaml
  - docker-compose.patroni.yaml
  - docker-compose.pgpool.yaml

# ═══════════════════════════════════════════════════════════════════
# VOLUMES COMPARTILHADOS
# ═══════════════════════════════════════════════════════════════════
volumes:
  # --- Volumes ETCD ---
  etcd-1-data:
      name: ${ETCD1_NAME}-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${ETCD1_DATA_PATH}
  
  etcd-2-data:
      name: ${ETCD2_NAME}-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${ETCD2_DATA_PATH}
  
  etcd-3-data:
      name: ${ETCD3_NAME}-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${ETCD3_DATA_PATH}

  # --- Volumes Patroni/PostgreSQL ---
  patroni-postgres-1-data:
      name: ${PATRONI1_NAME}-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PATRONI1_DATA_PATH}

  patroni-postgres-2-data:
      name: ${PATRONI2_NAME}-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PATRONI2_DATA_PATH}

  patroni-postgres-3-data:
      name: ${PATRONI3_NAME}-data
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PATRONI3_DATA_PATH}

  # --- Volume PgPool ---
  pgpool2-logs:
      name: pgpool2-logs
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PGPOOL_DATA_PATH}

# ═══════════════════════════════════════════════════════════════════
# NETWORKS COMPARTILHADAS
# ═══════════════════════════════════════════════════════════════════
networks:
  pg-ha-network:
    name: ${NETWORK_NAME}
    driver: bridge
