# ═══════════════════════════════════════════════════════════════════
# Cluster PostgreSQL com Patroni para Alta Disponibilidade (HA)
# Autor: Eduardo Richard
# Versão: v2.0 (2025)
# ═══════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════
# ÂNCORAS YAML (Templates Reutilizáveis)
# ═══════════════════════════════════════════════════════════════════

# --- PATRONI POSTGRES ANCORA ---
x-patroni-common: &patroni-common
  image: patroni-postgres:base
  build:
    context: ./infra/patroni-postgres
  networks:
    - pg-ha-network
  depends_on:
    etcd-1:
      condition: service_healthy
    etcd-2:
      condition: service_healthy
    etcd-3:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:8008/health || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 30s

# ═══════════════════════════════════════════════════════════════════
# SERVIÇOS
# ═══════════════════════════════════════════════════════════════════
services:

  # --- PATRONI POSTGRES NODES ---
  patroni-postgres-1:
    <<: *patroni-common
    container_name: ${PG1_NAME}
    hostname: ${PG1_NAME}

    environment:
      PATRONI_NAME: ${PG1_NAME}
      PATRONI_RESTAPI_URL: http://${PG1_NAME}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PG1_NAME}:5432
      
    env_file:
      - ./infra/patroni-postgres/config/.patroni.env

    ports:
      - "${PG1_API_HOST_PORT}:8008"
      - "${PG1_HOST_PORT}:5432"

    volumes:
      - patroni-postgres-1-data:/var/lib/postgresql/data/pgdata


  # --- PATRONI POSTGRES NODES ---
  patroni-postgres-2:
    <<: *patroni-common
    container_name: ${PG2_NAME}
    hostname: ${PG2_NAME}
  
    environment:
      PATRONI_NAME: ${PG2_NAME}
      PATRONI_RESTAPI_URL: http://${PG2_NAME}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PG2_NAME}:5432
    
    env_file:
      - ./infra/patroni-postgres/config/.patroni.env

    ports:
      - "${PG2_API_HOST_PORT}:8008"
      - "${PG2_HOST_PORT}:5432"
    volumes:
      - patroni-postgres-2-data:/var/lib/postgresql/data/pgdata


  # --- PATRONI POSTGRES NODES ---
  patroni-postgres-3:
    <<: *patroni-common
    container_name: ${PG3_NAME}
    hostname: ${PG3_NAME}

    environment:
      PATRONI_NAME: ${PG3_NAME}
      PATRONI_RESTAPI_URL: http://${PG3_NAME}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PG3_NAME}:5432
      
    env_file:
      - ./infra/patroni-postgres/config/.patroni.env
 
    ports:
      - "${PG3_API_HOST_PORT}:8008"
      - "${PG3_HOST_PORT}:5432"
    volumes:
      - patroni-postgres-3-data:/var/lib/postgresql/data/pgdata

# ═══════════════════════════════════════════════════════════════════
# NOTA: Volumes e Networks são gerenciados pelo docker-compose.yaml principal
# ═══════════════════════════════════════════════════════════════════