# ═══════════════════════════════════════════════════════════════════
# Docker Compose para Pgpool-II com Configuração Externalizada
# Autor: Eduardo Richard
# ═══════════════════════════════════════════════════════════════════

services:
  pgpool:
    image: pgpool:latest
    container_name: ${PGPOOL_NAME:-pgpool}
    hostname: ${PGPOOL_NAME:-pgpool}
    build:
      context: ./infra/pgpool
    restart: unless-stopped
    entrypoint: /opt/pgpool/bin/scripts/entrypoint.sh
    command:
      - "/opt/pgpool/bin/pgpool"
      - "-n"
      - "-f"
      - "/opt/pgpool/etc/pgpool.conf"

    # depends_on:
    #   patroni-postgres-1:
    #     condition: service_healthy
    #   patroni-postgres-2:
    #     condition: service_healthy
    #   patroni-postgres-3:
    #     condition: service_healthy
    
    # healthcheck:
    #   test: ["CMD-SHELL", "psql -h 127.0.0.1 -p 5432 -U healthcheck -c \"SHOW POOL_HEALTH_CHECK_STATS\" >/dev/null"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s

    volumes:
      - ./infra/pgpool/scripts:/opt/pgpool/bin/scripts:ro

      - ./infra/pgpool/config/pgpool.template.conf:/etc/pgpool2/pgpool.template.conf:ro
      - ./infra/pgpool/config/pcp.conf:/opt/pgpool/etc/pcp.conf:ro
      - ./infra/pgpool/config/pool_hba.conf:/opt/pgpool/etc/pool_hba.conf:ro

      - pgpool2-logs:/var/log/pgpool

    env_file:
      - ./infra/pgpool/config/.pgpool.env

    ports:
      - "${PGPOOL_HOST_PORT:-5432}:5432"
      - "${PGPOOL_PCP_HOST_PORT:-9898}:9898"
      
    networks:
      - pg-ha-network

volumes:
  pgpool2-logs:
      name: pgpool2-logs
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PGPOOL_DATA_PATH}

# ═══════════════════════════════════════════════════════════════════
# NETWORKS
# ═══════════════════════════════════════════════════════════════════
networks:
  pg-ha-network:
    name: pg-ha-network
    driver: bridge