# ═══════════════════════════════════════════════════════════════════
# Cluster PostgreSQL com Patroni para Alta Disponibilidade (HA)
# Autor: Eduardo Richard
# Versão: v2.0 (2025)
# ═══════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════
# ÂNCORAS YAML (Templates Reutilizáveis)
# ═══════════════════════════════════════════════════════════════════

# --- PATRONI POSTGRES ANCORA ---
x-patroni-common: &patroni-common
  image: patroni-postgres:base
  build:
    context: ./infra/patroni-postgres
  networks:
    - pg-ha-network
  depends_on:
    etcd-1:
      condition: service_healthy
    etcd-2:
      condition: service_healthy
    etcd-3:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:8008/health || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 30s

# --- RECURSOS DE CPU E MEMÓRIA ---
x-patroni-resources: &patroni-resources
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 4G

# ═══════════════════════════════════════════════════════════════════
# SERVIÇOS
# ═══════════════════════════════════════════════════════════════════
services:

  # --- PATRONI POSTGRES NODES ---
  patroni-postgres-1:
    <<: [*patroni-common, *patroni-resources]
    container_name: ${PATRONI1_NAME}
    hostname: ${PATRONI1_NAME}

    environment:
      PATRONI_NAME: ${PATRONI1_NAME}
      PATRONI_RESTAPI_URL: http://${PATRONI1_NAME}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PATRONI1_NAME}:5432
      
    env_file:
      - ./infra/patroni-postgres/config/.patroni.env

    ports:
      - "${PATRONI1_API_HOST_PORT}:8008"
      - "${PATRONI1_HOST_PORT}:5432"

    volumes:
      - patroni-postgres-1-data:/var/lib/postgresql/data/pgdata


  # --- PATRONI POSTGRES NODES ---
  patroni-postgres-2:
    <<: [*patroni-common, *patroni-resources]
    container_name: ${PATRONI2_NAME}
    hostname: ${PATRONI2_NAME}
  
    environment:
      PATRONI_NAME: ${PATRONI2_NAME}
      PATRONI_RESTAPI_URL: http://${PATRONI2_NAME}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PATRONI2_NAME}:5432
    
    env_file:
      - ./infra/patroni-postgres/config/.patroni.env

    ports:
      - "${PATRONI2_API_HOST_PORT}:8008"
      - "${PATRONI2_HOST_PORT}:5432"
    volumes:
      - patroni-postgres-2-data:/var/lib/postgresql/data/pgdata


  # --- PATRONI POSTGRES NODES ---
  patroni-postgres-3:
    <<: [*patroni-common, *patroni-resources]
    container_name: ${PATRONI3_NAME}
    hostname: ${PATRONI3_NAME}

    environment:
      PATRONI_NAME: ${PATRONI3_NAME}
      PATRONI_RESTAPI_URL: http://${PATRONI3_NAME}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PATRONI3_NAME}:5432
      
    env_file:
      - ./infra/patroni-postgres/config/.patroni.env
 
    ports:
      - "${PATRONI3_API_HOST_PORT}:8008"
      - "${PATRONI3_HOST_PORT}:5432"
    volumes:
      - patroni-postgres-3-data:/var/lib/postgresql/data/pgdata

# ═══════════════════════════════════════════════════════════════════
# NOTA: Volumes e Networks são gerenciados pelo docker-compose.yaml principal
# ═══════════════════════════════════════════════════════════════════